version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: postgres:12.4-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
  web:
    container_name: rubyPractice_web
    build: .
    tty: true
    volumes:
      - .:/rubyPractice
    ports:
      - "3000:3000"
    depends_on:
      - db
  volumes:
    db-data:
      drover: local