version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    
  web:
    container_name: rubyPractice_web
    build: nakahara_app
    volumes:
      - .:/rubyPractice
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
    driver: local